### ISSUE TITLE
关于python的.py文件打包成app文件的问题

### ISSUE THREAD

**Issue by yz666yz666** [Hurray0/Python-Chatroom#1]
您好，我们最近想对python文件进行打包，但总出现任何问题，试了所有的库都无法实现，想询问您关于打包app文件的办法。

**Comment by Hurray0** [comment]
什么环境？Mac吗？

**Comment by yz666yz666** [comment]
对，感谢回复。类似于这种情况，https://github.com/GameMaker2k/PyUPC-EAN/issues/4


在2018年05月6日 11:11，Hurray<notifications@github.com> 写道：

什么环境？Mac吗？

**Comment by yz666yz666** [comment]
使用的是py2app






发自网易邮箱大师


在2018年05月6日 11:11，Hurray<notifications@github.com> 写道：

什么环境？Mac吗？

**Comment by Hurray0** [comment]
直接用automator不行吗？

**Comment by yz666yz666** [comment]
没有用过这个，我尝试一下
在2018年05月6日 19:09，Hurray<notifications@github.com> 写道：

直接用automator不行吗？

**Comment by yz666yz666** [comment]
您好，是否可以分享一下详细使用Automator的详细打包过程？
在2018年05月6日 19:15，yz666yz666yz666<yz666yz666yz666@163.com> 写道：




没有用过这个，我尝试一下
在2018年05月6日 19:09，Hurray<notifications@github.com> 写道：

直接用automator不行吗？

**Comment by Hurray0** [comment]
写一个shell脚本运行python就可以了。。
请合理利用网络资源，谢谢
